variable "bastion_bastion_type" {}
variable "compartment_id" {}
variable "bastion_client_cidr_block_allow_list" {}
variable "bastion_dns_proxy_status" {}
variable "bastion_max_session_ttl_in_seconds" {}
variable "bastion_name" {}
variable "session_target_resource_details_session_type" {}
variable "session_target_resource_details_target_resource_fqdn" {}
variable "target_resource_operation_system_user_name" {}
variable "session_target_resource_details_target_resource_port" {}
variable "session_target_resource_details_target_resource_private_ip_address" {}
variable "session_display_name" {}
variable "session_key_type" {}
variable "session_session_ttl_in_seconds" {}
variable "test_target_resource_id" {}
variable "test_username" {}
variable "session_key_details_public_key_content" {}
variable "subnet_id" {}